AWSTemplateFormatVersion: "2010-09-09"

Resources:
  IAMGroup:
    Type: AWS::IAM::Group
    Properties:
      GroupName: TestIAMGroup
      ManagedPolicyArns:
       - arn:aws:iam::aws:policy/AdministratorAccess
      Policies:
       - PolicyName: BillingDenyPolicy
         PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Deny
            Action:
            - aws-portal:*
            - budgets:*
            - cur:*
            - ce:*
            - pricing:*
            - purchase-orders:*
            - awsbillingconsole:*
            Resource: "*"